Draft review for default extras PEP
astrofrog/peps pull request #1
Opened 2024-09-25 10:21 UTC by astrofrog

This is for initial collaboration on the PEP - leave comments/suggestions or open PRs to my branch to suggest changes/additions!

Preview: https://github.com/astrofrog/peps/blob/default-extras/peps/pep-tbd.rst

2024-09-25 10:30 UTC, pfmoore commented on peps/pep-tbd.rst
> +* ``package[-nondefault]`` - if ``nondefault`` is not specified as a default extra.
This is problematic, because it's not possible to determine if it's invalid without obtaining the `Default-Extras` metadata value (which in the case of a sdist, could require building the package).

It would be *much* better to say that this is valid, and define appropriate semantics for it (probably just "attempting to remove an extra that isn't defined, or isn't in the list of default extras, does nothing").

2024-09-25 10:33 UTC, pfmoore commented on peps/pep-tbd.rst
> +* ``package[pdf, -pdf]`` - an extra cannot be both negated and non-negated.
Why make this invalid? If the user tries to install two packages, one of which depends on `package[pdf] ` and the other depends on `package[-pdf]`, then you'll have effectively the same situation to deal with, and you won't be able to tell in advance. So you need to decide what the semantics are when *that* happens, and when you do, it won't be a problem to apply that same semantics to `package[pdf, -pdf]`.

2024-09-25 10:41 UTC, astrofrog commented
@pfmoore - thank you for taking a look at this already! I'll have a think about the two comments you left, and I was curious if you had any thoughts on the second alternative I just added in my last commit? Essentially I am wondering if we should leave it up to tools such as pip to provide a way to ignore extras, as this would avoid the complexity of adding a new syntax?

2024-09-25 10:43 UTC, pfmoore commented
Strong -1 on making it something tools have to do. There's already too many options, both in pip and in `uv`, and making it a tool option makes it impossible for one library to depend on another one without the default extras.

2024-09-25 10:46 UTC, pfmoore commented
To be honest, I think that in its current form, this PEP fails to cover the discussions that happened on the Discourse thread. You'll need to cover all the possibilities raised there before this is ready for submission - at a minimum, putting the various proposals that were made into the "Rejected Alternatives" section, and explaining what is wrong with them and why (in your opinion) your proposal satisfies the relevant use cases better.

2024-09-25 10:48 UTC, astrofrog commented
@pfmoore - sounds good, now that I have a skeleton I think I'll go through the discussion more systematically. Thanks for this initial review and feedback, it is very helpful!

2024-09-25 13:40 UTC, astrofrog commented on peps/pep-tbd.rst
> +* ``package[-nondefault]`` - if ``nondefault`` is not specified as a default extra.
I have updated this

2024-09-25 13:41 UTC, astrofrog commented on peps/pep-tbd.rst
> +* ``package[pdf, -pdf]`` - an extra cannot be both negated and non-negated.
Yes I agree with you, I have updated this to make it clear that the non-negated extra should always take precedence, and also that ``-`` does not mean a requirement of absence of dependencies, but just that an extra isn't needed (but might still get installed via some other dependency).

2024-09-25 13:51 UTC, astrofrog commented
@pfmoore - I have spent a few hours combing through the long discuss.python.org thread as well as several of the GitHub threads referred to, and have now tried to boil it down to the rejected alternatives in the latest version of this PEP. If you have time at some point I would be grateful if you could let me know if this is on the right track in your opinion.

2024-09-25 13:55 UTC, astrofrog commented
I'm also going to ping @RonnyPfannschmidt, @pradyunsg and @DEKHTIARJonathan as people who were specifically interested in writing/contributing to a PEP - please let me know if you'd like to join as authors, or either way if you have any feedback on this initial draft so far!

2024-09-25 14:38 UTC, RonnyPfannschmidt commented on peps/pep-tbd.rst
> +    Default-Extras: recommended,pdf
use multiple headers there instead of csv just like provides extra

2024-09-25 14:40 UTC, RonnyPfannschmidt commented on peps/pep-tbd.rst
> +One idea was to allow a special syntax to disable all default dependencies,
in my proposal i pososed a special form of `package[-, explicit ,list, of, extras]` as canonical form

the singular - denoting that default extras ought not to be considered for that particular requirement specifier

2024-09-25 14:43 UTC, RonnyPfannschmidt commented
a key hinge on moving my proposal forward was how to get backward compatibility with non-default-extra aware installers

multiple libraries i was working on would be "in hells kitchen" if they where just migrated to default dependencies without a way to ensure legacy installers supporting it

2024-09-25 16:50 UTC, abravalheri commented
It would be interesting to add in the rejected ideas section, why making the `extra` marker behave more similar to other markers - for example `extra != "name"` or `extra not in ("name", "other")` - is not viable.

2024-09-25 17:48 UTC, ethanhs-nv commented on peps/pep-tbd.rst
> +If both an extra and its negated version appear in an extras list, the
I think it would be better to disallow this. I expect making either an extra or its negation take precedence would lead to surprises for users.

2024-09-25 17:48 UTC, astrofrog commented
@abravalheri good idea, could you say in a few words why it would not be viable in your opinion?

2024-09-25 19:37 UTC, abravalheri commented
Hi @astrofrog , I don't know why not. That is why I was asking 😅.

That approach does not allow you to have a negative extra syntax, but allow you to have an extra that when specified exclude dependencies. For example:

```toml
dependencies = ["dep; extra != 'minimal']
```

```bash
pip install mypkg[minimal]
```

which has a very similar overall effect and could be used in similar usecases.

2024-09-25 19:50 UTC, astrofrog commented
@abravalheri - this would be nice but does it actually work for you? I just tried it in a real package and even when specifying ``[minimal]`` the dependencies with ``extra != 'minimal'`` got installed. But it's possible I'm doing something wrong so would be very interested to hear if you have it working in a real package.

2024-09-25 19:55 UTC, abravalheri commented
Exactly, that does not work now.

But it would be an alternative change (many people do try that approach intuitively and are disappointed by the results), so it would be interesting to understand why one alternative is prefered to other in the rejected ideas section.

2024-09-25 19:57 UTC, DEKHTIARJonathan commented on peps/pep-tbd.rst
> +If both an extra and its negated version appear in an extras list, the
Agreed with Ethan

2024-09-25 20:04 UTC, DEKHTIARJonathan commented
I think you're taking the requirement of this PEP a bit too far and it can be "greatly reduced" and consequently improved in its likelihood to be merged.

I would summarize the proposal as follows:

1. We don't need a "special magic no-extra" dictionary. Pick one of the followings:
    1. Either use `""` or `None`, consequently package installers like `PIP` can do: `if extra_requires is None or extra_requires == ""`
    This has the benefit to not change in any shape of way the specification of the `METADATA` file and make it fully backward compatible (to be noted: only updated "installers" can pick up the default extra).
    
    2. I would entirely remove this feature of `-extra`, extra-dependency sets are cumulative not subtractive. If you want to introduce this feature, please open a new PEP dedicated to this. It's out of scope. And frankly can introduce a crazy quantity of edge cases as @pfmoore highlighted.
    
     
In my opinion, keep it to the "core of the proposal" => providing a set of "optional dependencies" by default, unless some other set is required. 

CC: @ethanhs-nv

2024-09-25 20:10 UTC, astrofrog commented
@DEKHTIARJonathan - thanks for the feedback! Note that currently the meat of the proposal here is actually quite concise and many of the sections (including the empty string extras_require) are in rejected alternatives. The approach here (basically defining Default-Extras and defining a - syntax in extras lists) seemed to be the broad consensus of the discuss thread.

2024-09-25 20:19 UTC, DEKHTIARJonathan commented
@astrofrog I think your example can be improved `package[recommended]`.

I think we have a few much better use-cases: backends.
      - graphic backend: tkinter, etc.
      - compute backend: cpu/gpu, numpy vs cupy
      - communication backend: etc.
      etc.

These are prime examples of this "scenario" and probably the most interested parties.

A default "lightweight - simple" backend unless you ask for a backend larger/more specific.

2024-09-25 20:20 UTC, astrofrog commented
> a key hinge on moving my proposal forward was how to get backward compatibility with non-default-extra aware installers
> 
> multiple libraries i was working on would be "in hells kitchen" if they where just migrated to default dependencies without a way to ensure legacy installers supporting it

@RonnyPfannschmidt - is it correct that legacy installers would be fine with ``Default-Extras`` being present in the metadata since they would just ignore it? Are you referring to the fact that legacy installers would break if anyone used the ``-`` syntax in any of the dependencies? (for example if a package started declaring one of its dependencies as ``package[-pdf]``?)

If it is correct that legacy installers would be fine and ignore ``Default-Extras``, then maybe we should make it clear in the PEP that packages that start using the ``-`` syntax in their own dependencies will be implicitly breaking compatibility with legacy versions of e.g. pip? I see this more as a feature that would be useful for end users who are installing packages to choose what they want rather than packages specifying dependencies, though of course we can't stop the ``-`` feature being used in the latter.

2024-09-25 20:22 UTC, astrofrog commented
> Exactly, that does not work now.
> 
> But it would be an alternative change (many people do try that approach intuitively and are disappointed by the results), so it would be interesting to understand why one alternative is prefered to other in the rejected ideas section.

Ok sounds good, I'll try and write something up about this once I've had a chance to think about whether/why we can't do it

2024-09-25 20:24 UTC, astrofrog commented
@RonnyPfannschmidt - I also wanted to say that if you have an advanced draft that you think would be a better starting point than the one here, I'd be happy to switch over, so just let me know!

2024-09-25 20:27 UTC, DEKHTIARJonathan commented
> The approach here (basically defining Default-Extras and defining a - syntax in extras lists) seemed to be the broad consensus of the discuss thread?

No I absolutely don't think it was a consensus. It's what 1 person ( Pradyun ) mentioned. Then we brainstormed a bit about the idea. However this is an entirely new idea, syntax and concept. To me it doesn't have it's place here, it's hortogonal to "having default extra".

2024-09-25 20:29 UTC, astrofrog commented
@DEKHTIARJonathan - if we introduce a way to have default extras, we probably also need to provide a way to opt out of these, right? Otherwise aren't these just equivalent to moving the dependencies to ``install_requires``?

2024-09-25 20:32 UTC, DEKHTIARJonathan commented
@astrofrog 
> if we introduce a way to have default extras, we probably also need to provide a way to opt out of these, right? Otherwise aren't these just equivalent to moving the dependencies to install_requires?

No that's not how it should work. 

If you buy a car which buy default is `white`.
- Either you don't specify the color and get a white car
- You specify you want your car red and get the car red. (Not white and red, not -white and +red)

2024-10-12 17:45 UTC, NevilleS commented on peps/pep-tbd.rst
> +typical installation.
Just wanted to comment with some kudos: this is a really well written summary of **why** having the install 'by default'  include _more_ dependencies than one including an explicit extra, nice!

This is exactly how I'd use this PEP: to provide a 'by default' installation that includes multiple optional-but-usually-helpful dependencies, but still allow a more advanced 'minimal' install that excluded those.

Thanks for picking this up after a couple years of commentary 👍

2024-10-12 17:57 UTC, NevilleS commented
@DEKHTIARJonathan:
> I think the proposal should be simple:
> 
> A. If no `extra` is demanded - use the default set of extra (either by picking `None`, `""`, or `Default-Extras:` (my least favorite since it forces to change the METADATA file standard). `pip install my_pkg` => gets the `default extra`
> 
> B. If any extra is demanded => ignore the default, behave exactly like today `pip install my_pkg[A,B]` => gets `extras A and B` - default is ignored
> 
> C. We could consider adding `pip install my_pkg[]` or `pip install --no-default-extra my_pkg` => gets no `extra` at all including the default (essentially today). I'm not sure if there's a valid use-case for that, but if one is presented we could consider this

FWIW, I know I'm just wandering into an active discussion with a multi-year history, but I really agree with this. I think the "subtractive" syntax of `pip install my_package[-A]` is "interesting" but does add a lot of potential complexity. As a package maintainer I'd like to support a default `pip install my_pkg` with some default extras, and then discard those defaults entirely if an explicit extra is provides like `pip install my_pkg[A,B]`.

Also, your suggestion to use `None` or `""` as the syntax for a "default extra" seems reasonable to support backwards-compatibility. As someone without a lot experience in the complexities of Python packaging, I'd find `None` to be reasonably intuitive, so I think that's a win 👍.

2024-10-14 13:55 UTC, astrofrog commented
@NevilleS - thank you for the feedback!

@DEKHTIARJonathan - I've spent a while thinking about this and I thing I'm now on board with an approach where specifying any extras deselects the default extras. I think we have to do this, because otherwise introducing a new syntax in the package specification (e.g. ``-``) is going to cause any dependency tree that has a single package that uses this to fail with older pip versions. I'll update the PEP to instead describe the approach you are advocating.

@DEKHTIARJonathan @NevilleS - I don't think we can use a special string in the existing extras to mark a default - the reason is that the metadata gets stored as strings, so for example ``None`` won't work as a special marker since it's possible to write a package right now that would use ``None`` as a non-default extras name. In fact any other non-empty string won't work for the same reason - it's already possible to use it to define an extras.

That leaves empty string as the only possible other option - however I don't think this is desirable, because what if the user does want to include the default set of extras plus another? To give a concrete example, assuming you could somehow use an empty string as the extras name in a TOML file:

```
[project.optional-dependencies]
"" = [
    "scipy>=1.9.2",
    "matplotlib>=3.6.0"
]
more = [
    "pandas"
]
```

I think it would be weird for the user to have to do ``package[,more]`` (and I suspect using empty strings will cause lots of issues as it may already have meaning in various packaging systems). It's also then not possible to give your default set of dependencies a name. For example in my case I want an extras called ``recommended`` and I want that to be there by default, and to then also be able to do ``package[recommended, more]`` which is more explicit than say ``package[,more]``.

Having a magic string such as an empty string also restricts you to a single default extras, when in fact you might want to actually include several extras by default (for example several backends) and have the ability to just select one explicitly.

So for these reasons, I think we do need to add a new way to specify default extras that doesn't just rely on the name of the extras itself.

@DEKHTIARJonathan - would you be on board with this? If so, I can add you as a co-author next time I update the PEP along the lines above :slightly_smiling_face:

2024-10-15 09:58 UTC, pradyunsg commented
I appreciate the shape that this proposal has right now!

> is it correct that legacy installers would be fine with Default-Extras being present in the metadata since they would just ignore it?

Yes. We do need to bump the metadata version though.

> a key hinge on moving my proposal forward was how to get backward compatibility with non-default-extra aware installers

I think this is an important detail that we can not address. I think it's worth calling out as a behaviour of old installers.

> > if we introduce a way to have default extras, we probably also need to provide a way to opt out of these, right? Otherwise aren't these just equivalent to moving the dependencies to install_requires?
>
> No that's not how it should work.

I strongly disagree. I think what is in this proposal right now is the correct model.

> You don't "remove the default value" and add the value you want. The default value is only selected if you don't provide one.

Yea... But your example is using a constant string which can only have one value. It's not representative of what we're modelling here.

Our actual data is a sequence and we're changing what filters are being used by default. And, these filters are intended to be mechanisms for opting into functinality by ensuring the relevant dependencies are available -- in a theoretical future, using `rich[markdown]` should not mean that you can't use their syntax highlighting stuff anymore.

To use a different analogue: "Please add jalapeños to my pizza" does not mean "Remove all other toppings and add jalapeños to my pizza".

2024-10-15 11:47 UTC, astrofrog commented
I've now had a chance to take another pass at this. A few notes:

* I have implemented the approach that specifying extras deselects any default extras (suggested by several people including @DEKHTIARJonathan). It was not my preferred approach but I have come to realise it is the only one that will allow us to not completely break the packaging ecosystem with packaging tools that predate this PEP (introducing the ``-`` syntax for instance would cause all old packaging tools to break if any package in a dependency tree uses it)

* I have kept the proposal to update the core metadata to include ``Default-Extra`` and expanded the rejected alternatives to outline the proposal of using '' or None as 'special' extras name. The bottom line is that it's not possible to use '' because this would break backward compatibility (this was tested out and rejected in https://github.com/pypa/setuptools/pull/1503) and using e.g. ``None`` doesn't work because extras names are encoded as strings in the metadata so it would be no different from a ``'None'`` string, which might already be in use (even though it would be weird)

* @DEKHTIARJonathan - I've added you as a co-author, let me know if you are still happy with this.

* @RonnyPfannschmidt - regarding your comment in https://github.com/astrofrog/peps/pull/1#issuecomment-2374301662, I got stuck in the same place about backward compatibility with old installers, hence why I have updated the approach here.

2024-10-15 11:49 UTC, astrofrog commented
@pradyunsg - thank you for commenting on it just now! As you can see, I have changed the approach from your preferred one because the '-' syntax would create major backward-compatibility issues. However, I have of course kept the git history of this PR so if we can find a way to address that I can always revert back to the version you favored. Essentially the bottom line is that if a package deep in the python ecosystem was to start using ``-`` in its dependency list, all packages depending on it would suddenly no longer be usable with all but the most recent version of pip and other packaging tools. Do you think that is an acceptable break in compatibility?

2024-10-15 13:16 UTC, astrofrog commented
All right, so clearly the preferred approach is a contentious issue and there are strong feelings both ways :sweat_smile: 

I have therefore decided to take the following path forward: for now this PR contains drafts of two possible PEPs:

* **Option 1**: advocating for the use of the '-' syntax. This is the original version I had here and which @pradyunsg has been backing. I have now expanded the backward-compatibility section to discuss how I think we might be able to resolve this (by basically recommending that package developers hold off from using the - syntax for a bit until they are confident it won't affect many users downstream, and instead this syntax would be mostly useful to users setting up environments etc.)
* **Option 2**: advocating for the 'specifying an extra deselects defaults' approach suggested by @DEKHTIARJonathan 

If you favor one of the approaches, it would be great if you can help me try and finalize the PEP for that option, and once we get to the point where someone with sponsoring powers is happy with one of the versions, we pick that version and then properly propose the PEP to the Python community.

I hope this sounds reasonable!

2024-10-15 13:39 UTC, pfmoore commented
Neither of the two options are particularly appealing to me. The "deselect the default when you choose an extra" model feels unintuitive to me (I agree with @pradyunsg's pizza analogy) and it doesn't match how other languages such as Rust behave. On the other hand, the backward compatibility problems with the `-extra` syntax seem too significant to ignore.

Looking a bit more closely at Rust, I note that they don't have any way to deselect features individually - like extras, features are additive only. What they do have is a way of saying "don't include the default extras", either in a dependency specification, or in a command line invocation. Maybe we could do something similar, using the fact that installers (well, pip at least, I don't know about `uv`) ignore unknown extras, and define a "special" extra name, something like `:nodefault:`, that says "switch off the default extra"? That would be somewhat backward compatible, as the special name would be ignored - older installers would install the defaults when they shouldn't, but that may be acceptable.

This isn't a fully-fleshed out idea - `:nodefault:` isn't currently a valid extra name, so we'd be relying on tools being lax in their checking. But it might be worth exploring, as I don't think either of the current options are ideal.

2024-10-15 13:54 UTC, astrofrog commented
@pfmoore - I tried your specific example of ``:nodefault:``:

```
 pip install .[:nodefault:]
```

in a package, and got:

```
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[:nodefa'": Expected string_end
```

it looks like pip is somewhat strict about the syntax of extras, so I don't think this would work? (unless we can find a specific combination that would pass the packaging extras validator)

2024-10-15 14:07 UTC, pradyunsg commented
What version of pip is that?! We shouldn't have any references to `string_end` in those error messages.

2024-10-15 14:09 UTC, pradyunsg commented
Oh, hilarious. We get a giant traceback with the latest pip version. 😂

None the less, both uv and pip complain about a ":nodefault:" extra.

2024-10-15 14:11 UTC, astrofrog commented
A tongue-in-cheek option is to go through all packages on PyPI and find a word that isn't used in the extras of any package :laughing:

2024-10-15 14:15 UTC, astrofrog commented
Seriously though, looks like the latest version of pip does a very strict check of the extras against the PEP 508 syntax so I don't think there any any loopholes to exploit there.

Does anyone know if there would be precedent for disallowing the use of the - syntax in dependency lists for packages (e.g. in pyproject.toml, setup.cfg or equivalent) and only allowing it in e.g. pip commands, environment files, and so on? Because if there was such a distinction, we could always allow only the latter which would avoid backward-compatibility issues.

2024-10-15 14:24 UTC, pradyunsg commented
Package names can't start with a hyphen already.

2024-10-15 14:25 UTC, pradyunsg commented
https://packaging.python.org/en/latest/specifications/name-normalization/ is the relevant link.

2024-10-15 14:33 UTC, astrofrog commented
Sorry I should have explained myself better - is there any way we could allow the -extra syntax only in say pip commands, requirement files, or other environment files but disallow it in lists of dependencies in packages? I imagine not?

2024-10-15 14:37 UTC, pfmoore commented
> it looks like pip is somewhat strict about the syntax of extras, so I don't think this would work

Oh yeah, packaging is strict about syntax (for obvious reasons) I forgot about that. So whatever we do will be a compatibility issue, if we change the syntax of the extra list.

> Does anyone know if there would be precedent for disallowing the use of the - syntax in dependency lists for packages (e.g. in pyproject.toml, setup.cfg or equivalent) and only allowing it in e.g. pip commands, environment files, and so on?

No, that's never going to work. There's too many places where the distinction is blurred. And it would be a nightmare to document and explain. Plus, it doesn't solve the problem of people wanting to depend on just the base package with no default extras.

I think we have to accept that this will break backward compatibility. And once we've accepted that, we need to work out a transition process (and no, "tell people not to use it in dependencies for a while" *isn't* a sufficient plan...)

2024-10-15 15:24 UTC, DEKHTIARJonathan commented
@pfmoore @pradyunsg let's discuss a bit that `pizza analogy`.

If the cheese is default is tomato sauce on the pizza. Then it's not a "default extra", it's a base dependency ... 
I don't think it stands honestly ... To me it's more "the default comes with mozzarella if you don't specify anything, but if you do you can have `[mozzarella,mushrooms,jalapenos]`. But the tomato sauce is still included (and implicit).

What I mean is ... It's called * DEFAULT * extra - aka selected by default. Which means:

1. That you can also select it `manually` or let the default value be a default value

```python
def say_hello(name="John"):
    return f"Hello {name}"
    
assert say_hello() == say_hello(name="John") 
```

2. Override the default with something else:

```python
def say_hello(name="John"):
    return f"Hello {name}"
    
assert say_hello() != say_hello(name="Jane") 
```

3. Manually add the default plus smthg else.

```python
def say_hello(name: str | list[str] = "John"):
    if isinstance(name, list):
        name = " and ".join(name)
        
    return f"Hello {name}"
    
assert say_hello() != say_hello(name=["John", "Jane", "Jack"]) 
```

---------------------------

I think the "deactivate default value" logic is confusing at best ... Why would you even want to do that ?
I think we have to go back to first principles and think about the use cases that support this PEP.

This is primarily needed for packages that need a "sort-of" backend/frontend. Which means the most likely mode of operation is "request a backend/frontend manually or we'll assign the default to you".

2024-10-15 15:30 UTC, DEKHTIARJonathan commented
@astrofrog I think the proposal can be boiled down to a very simple "change" which hopefully shall be entirely backward compatible (to be confirmed).

- Forget about string magic value.
- Declare `extras` just as usual
- Add in the `pyproject.toml` (and consequently `METADATA` file) a new key `default_extra` that can be either:
     - empty / non existing (behavior non activated)
     - a comma-separated string
     
At install time, *if* no extra-deps is requested and `default_extra` is defined && non empty => you install `default_extra.split(",")`

That's it. I think it's the most minimal, and "achieve the goal" implementation. It's straightforward. And shall be entirely backward compatible (old versions of PIP will just ignore that new `default_extra` key)

2024-10-15 15:32 UTC, astrofrog commented
@DEKHTIARJonathan what you describe is the option 2 document in the PR here right? If not, feel free to comment on that document to suggest changes.

2024-10-15 15:35 UTC, DEKHTIARJonathan commented
@astrofrog if I understands well: yes.

The point being: logic gotta be simple & straightforward. Packaging is already complex enough ... This implementation allows literally anything you may have in mind. And it's fully backward compatible. And it's dead simple:

- Something is requested => don't use the "default value"
- Nothing is requested => use the "default value"

2024-10-15 15:37 UTC, pfmoore commented
> I think the "deactivate default value" logic is confusing at best ... Why would you even want to do that ?

Something like matplotlib that comes with various rendering backends. There's a default backend that's selected by default. If you are developing a new backend, you could definitely want to depend on "matplotlib without any default backend".

Basically, I don't think the "selecting a different extra disables the default" model works because it doesn't allow installing just the package with *no* extras (not even the default).

The problem here is that all of this has been discussed many times on Discourse and in this thread. We're not saying anything new at this point, just restating the fact that we haven't identified *any* solution that handles all of the stated use cases acceptably, and has a viable transition plan.

2024-10-15 15:43 UTC, astrofrog commented
> Basically, I don't think the "selecting a different extra disables the default" model works because it doesn't allow installing just the package with no extras (not even the default).

Regarding this specific point I think package maintainers do have the option of defining an empty extras (that is, with a name but no packages in it) that could be used for users who want a minimal install with no actual extras, eg package[minimal]

2024-10-15 15:47 UTC, astrofrog commented
In any case I agree we should not keep rehashing the same arguments at this point. Let's just try and see if we can push option 1 or option 2 over the line of 'viable'. For option 1 we need a clear transition plan, and I'll try and come up with something (after all, it was done for pyproject.toml and many packages nowadays would not be installable by pip a few years ago).

2024-10-15 15:48 UTC, DEKHTIARJonathan commented
@pfmoore 

> Something like matplotlib that comes with various rendering backends. There's a default backend that's selected by default. If you are developing a new backend, you could definitely want to depend on "matplotlib without any default backend".

I think that's kinda the point. A default is here if you don't specify anything. If we take back the example 

```python
def say_hello(name="John"):
    return f"Hello {name}"
```

You don't have the "option" to deactivate the default. Now as a library developer, you can entirely decide to not use that feature.

```python
def say_hello(name=None):
    return f"Hello {name}" if name else "Hello" 
```

Or more specifically to our case, nothing prevents this proposal to include: `pip install --no-default-extra mypkg` or have the library developers to include an empty `extra`: `empty = []` and have `pip install mypkg[empty]` 

I think this argument is philosophical - not technical. There is/are a/many solution(s). That would fix a problem for many libraries. Not only that but it would greatly improve user-experience for libraries who need a backend.

2024-10-15 15:55 UTC, DEKHTIARJonathan commented
@astrofrog I'm quite convinced - Option 1 - is impossible to get consensus. Too complicated. Too many opportunities for push back. I strongly strongly encourage you to pursue Option 2. 

You can already see ~ among people who agree that feature is needed ~ how difficult it is to find a good sweet spot.
I would keep it as simple as possible.

If later on in the process Option 2 ends up being a solution that would rally more of the community, nothing prevents you to take it out of the back pocket. But I would focus first on the most simple implementation & action plan.

2024-10-15 16:23 UTC, astrofrog commented
@DEKHTIARJonathan ultimately for either of these PEPs to fly, they will need to be sponsored by a Python core developer. So I am not the person who needs to be convinced of the merits of one option over the other!

I have decided for my mental health to remain open as either option would in my view be better than the status quo - I just want to make sure both proposals are made as polished as they can be and that we address any issues to the best we can and I'm then happy to then see if @pfmoore or @pradyunsg or others would be willing to sponsor either.

2024-10-15 16:25 UTC, astrofrog commented
In other words, let's not repeat arguments in the discussion of the PR. If you want to make a better case, then please help improve the PEP so that it speaks for itself.

2024-10-15 17:01 UTC, pfmoore commented
I'm likely to be PEP delegate for the PEP, so I don't think I should be sponsor as well (it's not forbidden, but there's a risk that it may be percieved as conflict of interest, plus it's more work than I really want to take on).

I will say that the backward incompatible `-extra` option would be *really* hard to argue for - I'd be very concerned about a good transition story for that one (which I don't think we're even close to). The "specifying an extra cancels the default" option is less of a problem technically, but needs to confirm that it actually satisfies people's use cases - it's all very well saying "projects can add an empty extra" but would they do so, would people be willing to use that, etc.? In other words, does it actually solve the problem people want it to solve? My impression is that you're being too casual about the "how do we say we want no extras" problem, but that's all it is - just an impression. You need to get feedback from the people who will actually need that capability.

2024-10-15 17:03 UTC, pradyunsg commented
FWIW, if you need a sponsor for the PEP, I'm happy to be the sponsor.

To that end, please don't open a PR against the canonical PEPs repository without getting an OK from me. :)

2024-10-15 18:41 UTC, astrofrog commented
@pfmoore that all makes sense, thanks! I'll keep working on it.

@pradyunsg thanks for offering to sponsor it! Just to check, is that regardless of which option we decide to pursue? I'll definitely wait until we/you are happy with it before opening a PR over at the main repo of course!

2024-10-15 19:36 UTC, NevilleS commented
@astrofrog: once again, thanks for picking this up and running with it! I hope you can see that the commenters here are vigorously debating because they want this to exist and it's because of you that's happening. FWIW, I believe we all feel that Option 2 (aka `Default-Extra` but without the `-extra` syntax to deselect) is the only viable option and therefore you can safely update the PEP and conserve your maintainer energy to only focus on that one ❤️

With that in mind, I'd ask: what are the biggest downsides of Option 2? I think it's this issue that @pfmoore has wisely flagged:
> Basically, I don't think the "selecting a different extra disables the default" model works because it doesn't allow installing just the package with no extras (not even the default).

That's a completely fair argument, and I agree it's a philosophical debate that we'll never all agree on a default behaviour that works for _all_ packages. To restate the problem: if the maintainer of `package` decides to add a `Default-Extra: recommended`, the behaviour of `pip install package` will _change_ and act as if the user had specified `pip install package[recommended]`. That's *exactly* what maintainers like @DEKHTIARJonathan and myself (@NevilleS) want for our packages (so we're happy with that) but it opens the door to confusing maintainers who might want a different default, or users who might want to install a package with no extras.

I think the PEP would allow at least four options to address this "no extras" problem without major changes:
1. Maintainers can opt not to use `Default-Extra` at all, and the current behavior will continue unaffected. Each maintainer can decide what's right for their package
2. Maintainers can add a specially named extra like `minimal` or `empty` and document this in their project to allow users to use `pip install package[minimal]` if those users don't want the default extras. Note that this is the inverse of what maintainers do today, which is to add specially named extras like `recommended` and encourage users to use `pip install package[recommended]` to get the equivalent of default extras today
3. Maintainers can publish a sibling package like `package-slim` that excludes all defaults to allow users to use `pip install package-slim`. This seems pretty uncommon today but I found one example here with `pip install typer` and `pip install typer-slim`: https://github.com/fastapi/typer?tab=readme-ov-file#typer-slim
4. Depending on installer support, users could use a command-line argument with installers like `pip` (and others) to disable default extras, like `pip install --no-default-extra package`

My $0.02 would be that **since the proposed "default extras" feature would be on an opt-in basis for each package**, all of these choices would be available to maintainers would have enough tools available to decide whether they want the default for their project to be "extras included" or "no extras", and the PEP doesn't need to pick sides in that philosophical debate...

@pfmoore: does that counter-argument make sense to you?

2024-10-15 19:59 UTC, pfmoore commented
> @pfmoore: does that counter-argument make sense to you?

To be clear, I have no direct need for any of this. I'm simply reporting points that were made by others in the Discourse thread[^1]. The important thing is that somebody asks the people who originally requested this capability whether it satisfies their use cases. Everyone on this issue may think that the workaround of an "empty" extra is sufficient, but that's irrelevant if project maintainers and/or users hate the idea.

That's part of the job of creating a PEP - getting buy-in from the users affected by the proposal.

[^1]: And I may be misremembering things...

2024-10-15 21:28 UTC, NevilleS commented
OK, thanks @pfmoore: I misread your comment as-if you could represent the "others" here 😄, that's fair!

In that case, I think the right next step would be to amend the PEP to simplify it down to just the `Default-Extra` proposal and remove the language around deselecting extras (ie Option 2) and share that back with the Discourse thread. Personally I think that strikes a reasonable balance: it allows package maintainers to opt-into a new default for their project, but those who prefer the current style of "no extras" being the default can decide not to use it.

2024-10-15 21:54 UTC, astrofrog commented
@NevilleS you are definitely being helpful, thank you! I will try and tidy things up shortly 😀

2024-10-16 10:16 UTC, astrofrog commented
@NevilleS - I have removed option 1 and updated option 2, to now include some specific example applications of the PEP, as I think this will be important for convincing maintainers that this is versatile and should solve several different real-life use cases. Would you be happy to take a look at the PEP as it stands to see if you are happy with it?

@DEKHTIARJonathan - as a co-author, could you now read through carefully to make sure you are happy with it and make any suggestions if needed? Note that the 'meat' of the proposal is very simple as you were saying - the PEP is just long-ish because it's important to mention the rejected alternatives and also give some real-life applications of it.

I am also going to send an update to the thread to solicit feedback from other people who were originally involved in the conversation.

2024-10-16 10:18 UTC, astrofrog commented
Also @pradyunsg would you be able to take a look at check that you would be happy with this approach and likely to sponsor it once we have converged?

2024-10-16 10:47 UTC, astrofrog commented
If anyone wants to see the rendered version, it is at https://astrofrog.github.io/peps/pep-9999/

2024-10-17 11:25 UTC, hamogu commented
I don't have any specific comment on how exactly this is implemented, but I want to just comment that the general concept would have been very helpful for me a while ago. 

I have a package with some somewhat esoteric dependencies for a graphics backend. I'd love to make all the packages needed for that backend the default so that "it just works" for all users, but I can't because that causes complications for CI and for those very few users who cannot match the requirements for that backend because some of its dependencies is not available for e.g. windows.

Currently, I've solved the problem by re-doing the implementation of graphic output to rely on some other graphics package (which I can add to "minimal" because it's available everywhere), but it's very annoying that essentially the limitations of pip determine which graphics package I can and cannot use as the default.

2024-10-26 16:33 UTC, neutrinoceros commented on peps/pep-9999.rst
> +defaults would provide a much better experience for users.
I read this yesterday and couldn't think of an actual package that does this. I just found one today; `viscm` needs to be installed with either extra `PyQt` or `Pyside`, but isn't functional on its own. Just in case you need a concrete example here.

2024-10-26 16:53 UTC, astrofrog commented on peps/pep-9999.rst
> +defaults would provide a much better experience for users.
Thanks! Same with glue - I wasn't sure if I should single out specific packages in a PEP though?

2024-10-26 16:59 UTC, neutrinoceros commented on peps/pep-9999.rst
> +defaults would provide a much better experience for users.
I think it's okay (especially if you can give more than one illustration); I believe I've seen it done in other packaging-related PEPs.

2024-11-11 12:30 UTC, astrofrog commented
@DEKHTIARJonathan - could you confirm whether you are happy with the PEP as-is and happy to be a co-author?

@pradyunsg - how do you feel about the PEP as is stands right now? What do you think should be the next steps before we can open a PR to the canonical PEP repo?

2024-11-13 00:42 UTC, warsawnv requested changes
This is a good start!  I have added some comments to think about, but also, the PEP is missing some [sections defined in PEP 12](https://peps.python.org/pep-0012/#suggested-sections), specifically "How to Teach This" and "Copyright".   Best to stick to the section names and ordering for the sections that do appear here.

2024-11-13 00:42 UTC, warsawnv commented on peps/pep-9999.rst
> +extensively at https://discuss.python.org/t/adding-a-default-extra-require-environment/4898/38.
```suggestion
extensively on `this DPO thread <https://discuss.python.org/t/adding-a-default-extra-require-environment/4898/38>`__.
```

2024-11-13 00:42 UTC, warsawnv commented on peps/pep-9999.rst
> +install the package using ``package[recommended]``, while those who prefer more
Possibly covered later (in which case, ignore), but why is the proposed approach better than something like `package[minimal]` or `package[default]`?

2024-11-13 00:42 UTC, warsawnv commented on peps/pep-9999.rst
> +defaults would provide a much better experience for users.
> Just in case you need a concrete example here.

Concrete existing examples would help with the motivation.

2024-11-13 00:42 UTC, warsawnv commented on peps/pep-9999.rst
> +as follows in a ``pyproject.toml`` file:
I think this PEP should take a stronger stance for proposing `pyproject.toml` syntax for default dependencies, especially in light of the recent acceptance of [PEP 735](https://peps.python.org/pep-0735/) which defines dependency groups.  In fact, perhaps something like:

```toml
[dependency-groups]
default-extras = [
    'foo',
    'bar',
]
```

could be possible syntax.

But even if not, I think some mention of this PEP's relationship to PEP 735 is needed.

2024-11-13 03:16 UTC, pradyunsg commented on peps/pep-9999.rst
> +as follows in a ``pyproject.toml`` file:
> [dependency-groups] default-extras 

FWIW, I'm strongly opposed to having _this_ specific syntax here.

That said, I agree that this PEP should also be standardising the project table key here.

> But even if not, I think some mention of this PEP's relationship to PEP 735 is needed.

FWIW, I'm in the camp of folks who think that allowing mixing of dependency groups and extras is a recipe for user confusion.

Plus, as it stands, PEP 735 does not affect package metadata so (IMO) the only valid stance in this PEP is "there are no effects to consider".

2024-11-13 03:45 UTC, pradyunsg commented
> @pradyunsg - how do you feel about the PEP as is stands right now?

Thanks for your patience on me getting back.

FWIW, I'm not 100% sure about the currently proposed design and need a bit of time to think about what's bothering me about it (so that I can make a specific suggestion / resolve what's bothering me). To err on the side of overcommunicating, this isn't a blocking concern in any way for submitting the PEP.

I did realise that there's one approach that we haven't considered in the PEP: making a single specific extra name special, and having it get selected by default.

I think that's worth either marking as rejected, making the PEP use that, or adding as an open question. I'm not sure what my specific position is right now on this idea, but I might lean in a particular direction later today. 😅

> What do you think should be the next steps before we can open a PR to the canonical PEP repo?

I think this needs one more round of updates, and then we can submit the PR!

I expect to see a few copy editing suggestions from the PEP editors, and I'll share some more code-review style feedback once I'm in front of a proper keyboard, rather than trying to reviewing this on my phone.

I've marked out some time today to take a look at this properly again but that's also a bit before I need to hop on a flight, so I might only be submitting the review at, like, 21:00 UTC or something. 😅

2024-11-13 15:12 UTC, astrofrog commented on peps/pep-9999.rst
> +install the package using ``package[recommended]``, while those who prefer more
@warsawnv - just to check, did the rest of the PEP answer this? This PEP in fact enables ``package[minimal]``, without this PEP it is impossible to make ``package[minimal]`` be a more minimal installation than ``package`` on its own. Does this make sense?

2024-11-13 15:15 UTC, astrofrog commented
@warsawnv - thank you for the review!

@pradyunsg - thank you for the update! I'll refrain from making any changes until you've had a chance to submit your review. Regarding your comment:

> I did realise that there's one approach that we haven't considered in the PEP: making a single specific extra name special, and having it get selected by default.

I think this is somewhat covered in the section **Adding a special entry in ``extras_require``** - do you agree? Or do you mean something different?

2024-11-18 17:36 UTC, vyasr commented on peps/pep-9999.rst
> +defaults would provide a much better experience for users.
An example where this is not currently done but could be useful in the future in a pretty high-impact area is with switching between BLAS/LAPACK implementations, for example in numpy/scipy. In those cases it is also not done yet due to additional considerations (ABI compat etc), but it may still be a useful example. Alternative FFT implementations (e.g. pyfftw) could be another useful example.

2024-11-18 17:40 UTC, vyasr commented on peps/pep-9999.rst
> +should be installed even if other occurences of the package in the dependency
```suggestion
should be installed even if other occurrences of the package in the dependency
```

2024-11-20 21:44 UTC, DEKHTIARJonathan requested changes
Thanks immensely for your work @astrofrog. I'm almost 100% thumbs up.

I added a few remarks in comments. Please let me know if I can help addressing them.

In addition, a few people I talked about suggested we add a section to reinforce that `package conflict` is a problem existing today and is out of scope for this PEP.

For example @neutrinoceros was mentioning `viscm` needs either `PyQt` or `Pyside` but probably not both simultaneously, both are "conflicting". And obviously today nothing prevents `pip install viscm[pyqt,pyside]` if these extras do exist. Let's reinforce that this is an existing problem that this PEP does not plan on addressing (and could be addressed in a subsequent PEP)

2024-11-20 21:44 UTC, DEKHTIARJonathan commented on peps/pep-9999.rst
> +        Jonathan Dekhtiar <jonathan@dekhtiar.com>
![image](https://github.com/user-attachments/assets/ec2cb2de-24c6-4115-b30c-3acb3535f0e0)
There's probably a need to adjust the formatting differently. I don't think that's how you intended it renders. Probably you have to put line 3 & 4 on the same line 

See how PEP 683 is doing it: https://raw.githubusercontent.com/astrofrog/peps/435dfce9e9f727c1458021e681f336021872f952/peps/pep-0683.rst

2024-11-20 21:44 UTC, DEKHTIARJonathan commented on peps/pep-9999.rst
> +install the package using ``package[recommended]``, while those who prefer more
@astrofrog I do think we should add a few words along the lines "a solution will be detailed later on how to go about this problem".

We don't have to get into the specifics here, however mentioning that there should be a way to "deactivate" this behavior is a good idea IMHO.

2024-11-20 21:44 UTC, DEKHTIARJonathan commented on peps/pep-9999.rst
> +defaults would provide a much better experience for users.
Agreed with Vyas & Barry.

@astrofrog can we add a few of the aforementioned examples ?

2024-11-20 21:44 UTC, DEKHTIARJonathan commented on peps/pep-9999.rst
> +    Default-Extra: backend1
No opinion here. Is it better for any reason to do:

```
Default-Extra: backend1
Default-Extra: backend2
Default-Extra: backend3
```

Instead of:
```
Default-Extra: backend1,backend2,backend3
# or
Default-Extras: backend1,backend2,backend3
```

It might be an implementation artifact of how METADATA works, is there a "reason" to go for one over the other ?

2024-11-20 21:44 UTC, DEKHTIARJonathan commented on peps/pep-9999.rst
> +Alternatives`_ section for the rationale).
I think before switching to the next section, we should add a subsection "solution to install without default"

2024-11-21 12:27 UTC, astrofrog commented on peps/pep-9999.rst
> +    Default-Extra: backend1
I originally had it as comma-separated values but changed it following @RonnyPfannschmidt's suggestion in https://github.com/astrofrog/peps/pull/1#discussion_r1775362470 - I don't have strong opinions

2024-11-21 13:03 UTC, pfmoore commented on peps/pep-9999.rst
> +    Default-Extra: backend1
Comma separated is not the norm for metadata items. I'd stick with a multiple-use field.

2024-11-21 15:12 UTC, DEKHTIARJonathan commented on peps/pep-9999.rst
> +    Default-Extra: backend1
Fair with me. Let's keep that way you can resolve this comment. Thanks for the pointers

2024-11-21 22:25 UTC, astrofrog commented
@pradyunsg - just to double check, have you started reviewing this? If not, I might implement some of the existing review comments from others in the next couple of days - but if you have already started a review, I will wait for it before making any changes.

2024-11-21 22:44 UTC, pradyunsg commented on peps/pep-9999.rst
> +    Default-Extra: backend1
The former is a supported thing in the email header format, thus does not require additional parsing on the part of downstream consumers of the format.

Besides that, I don't think there's any no strong reason to have an invented mini-format (eg: do we strip whitespace around commas, are any other separators valid, etc) when the overall format supports the relevant functionality transparently.

2024-11-21 22:46 UTC, pradyunsg commented
> just to double check, have you started reviewing this? 

I have, but don't wait on me to update this. :)

2024-11-22 11:15 UTC, neutrinoceros commented
A random observation in the wild: `typer`'s documentation looks like it could use this PEP:

> Its only internal required dependency is [Click](https://click.palletsprojects.com/).
> By default it also comes with extra standard dependencies

see https://typer.tiangolo.com/#dependencies

given [how popular this framework is](https://pypistats.org/packages/typer), it might be worth mentioning in passing.

2024-11-22 13:57 UTC, astrofrog commented on peps/pep-9999.rst
> +install the package using ``package[recommended]``, while those who prefer more
Sounds good, I have rephased this sentence to also not make it sound like 'one current solution' was the goal of this PEP, but rather a solution in the current status quo. I have also added a sentence to say that the goal of this PEP is to solve this.

2024-11-22 13:57 UTC, astrofrog commented on peps/pep-9999.rst
> +        Jonathan Dekhtiar <jonathan@dekhtiar.com>
Fixed (I'll push my changes once I have finished implementing all of them)

2024-11-22 14:11 UTC, astrofrog commented on peps/pep-9999.rst
> +defaults would provide a much better experience for users.
I've added some concrete examples

2024-11-22 14:19 UTC, astrofrog commented on peps/pep-9999.rst
> +Alternatives`_ section for the rationale).
I added a new section 'Installing without default extras'

2024-11-22 14:32 UTC, astrofrog commented on peps/pep-9999.rst
> +as follows in a ``pyproject.toml`` file:
I've added a new section to the PEP, 'New key in ``[project]`` metadata table' (will push shortly)

2024-11-22 15:12 UTC, astrofrog commented
@warsawnv @DEKHTIARJonathan @vyasr - thanks for the detailed reviews!

I have just pushed some changes - the main ones are:

* Added specific examples of multiple frontends/backends
* Normalized section names to match those defined in PEP 12 and re-ordered a couple of sections as a result.
* Added Rationale, Security Implications, and Copyright sections
* Add a specification for ``[project]`` metadata

There are some smaller changes motivated by comments in the reviews above. I believe all comments have been addressed or resolved above, but let me know if you feel I missed anything!

2024-11-22 15:17 UTC, astrofrog commented
I've updated the preview at https://astrofrog.github.io/peps/pep-9999/

2024-12-18 00:04 UTC, vyasr approved these changes
I left a number of small changes to improve wording and style, but overall the content looks great to me now.

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +extensively on `this DPO thread <https://discuss.python.org/t/adding-a-default-extra-require-environment/4898/38>`__.
Is it worth listing other potential use cases without the same level of elaboration as the two below, or do you think that would simply muddle the proposal without adding any value?

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +frontends, and dependencies that need to be installed for each backend or
```suggestion
Another common use case for using extras is to define different backends or
frontends and dependencies that need to be installed for each backend or
```

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +way to specify one or more default backend or frontend and providing a way to
```suggestion
With current packaging standards, maintainers have to either
require one of the backends or frontends, or require users
to always specify extras, e.g. ``package[backend]`` and therefore risk users
having an unusable installation if they simply install ``package``. Having a
way to specify one or more default backend or frontend and providing a way to
```

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +and this PEP does not change this.
```suggestion
infrastructure to disallow conflicting or incompatible extras to be installed,
and this PEP does not change that.
```

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +packaging infrastructure in any significant way. It is an opt-in solution which
I haven't been involved in the prior conversations so perhaps I didn't see the discussions that led to this acknowledgment, but naively it doesn't seem like it adds much here. If you're concerned about getting philosophical pushback from particular reviewers though feel free to keep it.

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +``default-optional-depencencies`` with the following description:
```suggestion
``default-optional-dependencies`` with the following description:
```

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +Each string in ``default-optional-depencencies`` should be the name of an extra
```suggestion
Each string in ``default-optional-dependencies`` should be the name of an extra
```

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +First, we consider the case of packages that want users to get recommended
```suggestion
First, we consider the case of packages that want recommended
```

2024-12-18 00:04 UTC, vyasr commented on peps/pep-9999.rst
> +there would be an extras explicitly specified, would mean the default extras
```suggestion
there would be an extra explicitly specified, would mean the default extras
```

2025-01-10 11:01 UTC, astrofrog commented on peps/pep-9999.rst
> +extensively on `this DPO thread <https://discuss.python.org/t/adding-a-default-extra-require-environment/4898/38>`__.
I think that the two use cases I mentioned actually cover most of the ones I saw in the various discussions - the second discussion on multiple front-ends or backends is broad enough to cover several cases that were mentioned such as having different computational backends, or different GUI frameworks and so on. I have reworded this to say:

_Various use cases for default extras and possible solutions in this PEP were discussed
extensively on `this DPO thread <https://discuss.python.org/t/adding-a-default-extra-require-environment/4898/38>`__.
These fall into two broad cases that that provide the
motivation for the present PEP._

to not make it sound like I just cherry picked two use cases and ignored others. The two use cases here are a synthesis of the different cases I saw in the discussion. However if anyone would like to bring up another distinct use case, I'd be happy to add it!

2025-01-10 11:04 UTC, astrofrog commented on peps/pep-9999.rst
> +packaging infrastructure in any significant way. It is an opt-in solution which
Let's just say there has been some philosophical pushback :sweat_smile: - obviously I'd be happy to remove this if people object to including it, but until we get to the point where we have some kind of consensus, it might be safer to keep.

2025-01-10 11:05 UTC, astrofrog commented
@vyasr - thank you for the review!

2025-01-10 11:16 UTC, astrofrog commented
I have updated the preview for anyone wishing to read over this now: https://astrofrog.github.io/peps/pep-9999/

2025-01-10 13:30 UTC, pradyunsg reviewed
A few comments. Let's file a PR against python/peps once these are resolved -- let's get to a d.p.o thread soon. :)

2025-01-10 13:30 UTC, pradyunsg commented on peps/pep-9999.rst
> +    default-optional-dependencies = [
I'm not a huge fan of this name, since this is listing the keys under `optional-dependencies` rather than PEP 508 strings. OTOH, I think we can pick the bike shed color in the d.p.o. thread. :)

2025-01-10 13:30 UTC, pradyunsg commented on peps/pep-9999.rst
> +Sponsor: TBD
```suggestion
Sponsor: Pradyun Gedam <pradyunsg@gmail.com>
```

2025-01-10 13:30 UTC, pradyunsg commented on peps/pep-9999.rst
> +extra, then if a user was to install the package with::
```suggestion
If extras are explicitly given in a dependency specification, the default extras are not installed. Otherwise, the default extras are used.

For example, if a package
defines a ``extra1`` default extra as well as a non-default ``extra2``
extra, then if a user was to install the package with::
```

A suggested rephrasing to avoid saying this is a proposal (in a subsection called specification) + to call out the behaviour separately from the examples.

2025-01-10 13:30 UTC, pradyunsg commented on peps/pep-9999.rst
> +-------------------------
```suggestion
Teaching package authors
------------------------
```

2 things: "teaching to" does not read as valid English grammar to me & I think it's worth being specific about what the specific user we care about (authors vs consumers, i.e. if it's the people uploading packages or people downloading packages).

2025-01-10 13:30 UTC, pradyunsg commented on peps/pep-9999.rst
> +The simple rule above regarding only installing default extras when no extras
Suggestion: Follow the guidance in https://justsimply.dev and removing the use of "just" / "simple" and similar words from this entire PEP.

2025-01-10 13:30 UTC, pradyunsg commented on peps/pep-9999.rst
> +--------------------------------------------
I think this section should cover why "default" is not a good name for the special entry here.

2025-01-10 14:09 UTC, astrofrog commented on peps/pep-9999.rst
> +    default-optional-dependencies = [
Yes I see what you mean - I have no strong opinion here and happy to update it if someone comes up with a better suggestion.

2025-01-10 14:23 UTC, astrofrog commented on peps/pep-9999.rst
> +The simple rule above regarding only installing default extras when no extras
Done, I have checked for these and other similar words

2025-01-10 14:23 UTC, astrofrog commented on peps/pep-9999.rst
> +--------------------------------------------
I have made a tweak to this section to change:

_In addition, no other string can be used as a special
string since all strings that would be a backward-compatible valid extras name
may already be used in existing packages._

to

_In addition, no other string (such as ``'default'``) can be used as a special
string since all strings that would be a backward-compatible valid extras name
may already be used in existing packages._

Hopefully this addresses your comment?

2025-01-10 14:30 UTC, astrofrog commented
@pradyunsg - thank you for the review and for officially agreeing to sponsor this! Could you confirm once you are happy that your comments are addressed, and I can go ahead and open a PR to the main PEP repo?

One small technicality I don't quite understand - in the [PEP submission guidelines](https://peps.python.org/pep-0001/#submitting-a-pep) it says that I should pick a number for the PEP when submitting the PR which is neither used in the repo or in an existing open PR. However, it also says 'Once approved, they will assign your PEP a number' (about the PEP editors). Is it that I should attempt to pick a valid number and that after their review process they confirm whether the number is ok or whether to use another one?

2025-01-10 14:33 UTC, astrofrog commented
Another question is whether you think I should start working on a reference implementation before opening the PR to the main PEP repo, or whether it is premature to do this?

2025-01-10 21:50 UTC, pradyunsg commented
> Is it that I should attempt to pick a valid number and that after their review process they confirm whether the number is ok or whether to use another one?

Yup, you can pick the next available PEP number (currently 790, I think?) and if two PRs use the same number for different content, the PEP editors will provide guidance to resolve the conflict. :)

> Another question is whether you think I should open PRs with a reference implementation and adding the links here before opening the PR to the main PEP repo, or whether it is premature to do this?

Neat! I'd say it'd be best link to your branches from the initial PEP draft, that is submitted to the main PEPs repo. It doesn't need to be a PR to flit/pip _right now_, and a PoC "look, it works" would be better for initiating the discussion (I'm partly concerned about the discussion spreading across to happen on the PRs rather than just the d.p.o thread).


> I can go ahead and open a PR to the main PEP repo?

Yup! And, go ahead and add links to the draft implementations in pip/flit, if you're OK with the approach suggested above.

2025-01-10 21:51 UTC, pradyunsg commented on peps/pep-9999.rst
> +--------------------------------------------
I can't click the resolve button... so... yes. :)

2025-01-10 22:32 UTC, astrofrog commented
@pradyunsg - thanks! That all sounds good 😄

2025-01-13 15:11 UTC, astrofrog commented
@pradyunsg - I've now opened a PR to the PEP repository in https://github.com/python/peps/pull/4198

Thanks everyone for all your comments and helping make it to this stage!

2025-01-13 15:12 UTC, astrofrog commented
If anyone is interested, I've now populated the reference implementation section with links to flit/pip forks which seem to work.

2025-01-13 16:23 UTC, DEKHTIARJonathan commented
@astrofrog can we make the reference implementation installation : `pip install pep-771` ?

2025-01-13 16:24 UTC, astrofrog commented
Well the implementation needs forks of pip and flit so I'm not sure if we can make it easily installable like this?

2025-01-13 23:53 UTC, DEKHTIARJonathan commented
@astrofrog it's possible I'm working on it. Gimme a few days

2025-02-05 13:16 UTC, astrofrog commented
I am going to close this as the PEP is now published (and undergoing some updates in a separate PR). Thanks everyone for the discussion on here!

2025-02-05 13:16 UTC, closed without merging